### ISSUE TITLE
Can you share a dummy non-empty dataset for testing?

### ISSUE THREAD

**Issue by bozcani** [koraykzly/eksi-sozluk-clone#1]
Great work, Koray! Eline saglik!

I have downloaded the repo and run front-end and back-end separately. Is the fake data coming from the backend? Can you export and upload a fake dataset so that we can use it for tests.

**Comment by koraykzly** [comment]
Hello İlker, thanks a lot. 

I didn't care this project for a long time, most of the functions probably not implemented yet. I add a postgres script to populate database. Enjoy!

**Comment by bozcani** [comment]
Thanks! It works well :+1:
